# Generated by Django 3.0.8 on 2020-10-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegistraion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_no', models.IntegerField()),
                ('email_id', models.EmailField(max_length=30, unique=True)),
                ('city', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('marks', models.FloatField()),
                ('roll_num', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_By', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
