# Generated by Django 3.0.8 on 2020-10-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
